Auto install
QuiiBz/sherif pull request #71
Opened 2024-06-29 22:18 UTC by Willem-Jaap

Closes https://github.com/QuiiBz/sherif/issues/38 & https://github.com/QuiiBz/sherif/issues/68

This is my first time writing Rust so feel free to help me learn😅

Right now the implementation asks the user if they want to run install and tries to detect the package manager.
 
![image](https://github.com/QuiiBz/sherif/assets/67187467/d065ece9-ed00-4a35-b058-7b0a70e5eb61)

Still draft as I want to add more tests but welcome to initial feedback!

2024-06-30 06:57 UTC, QuiiBz requested changes
Thanks for the PR, and glad that it's your first time writing Rust!

Could you change the behavior to automatically run an install after `--fix` is run, unless we pass `--no-install`? We don't need to ask the user given we'll already have an option to disable it.

2024-07-01 08:27 UTC, Willem-Jaap commented
Install now runs automatically. Will add some more tests and polish when I have the time

2024-08-10 07:04 UTC, QuiiBz requested changes
Sorry for the huge delay on this PR, here's some feedback.

I wonder why we didn't already have `-f` as a shorthand for `--fix`, great addition 👍

2024-08-10 07:04 UTC, QuiiBz commented on src/install.rs
> +fn detect_package_manager () -> String {
What do you think of introducing an `enum` instead of a `String` for the package managers? It would also have a `None` variant, instead of returning an empty string in case we haven't found the package manager.

2024-08-10 07:04 UTC, QuiiBz commented on src/install.rs
> +
I think we should add `bun` too.

2024-08-10 07:04 UTC, QuiiBz commented on README.md
> +Most issues can be automatically fixed by using the `--fix` flag. Sherif tries to auto-detect your package manager and runs install. Note that autofix is disabled in CI environments (when `$CI` is se
```suggestion
Most issues can be automatically fixed by using the `--fix` (or `-f`) flag. Sherif tries to auto-detect your package manager and run its `install` command. Note that autofix is disabled in CI environments (when `$CI` is set):
```

2024-08-10 07:04 UTC, QuiiBz commented on README.md
> +When you don't want Sherif to install packages after running autofix, you can use the `--no-install` flag:
```suggestion
If you don't want Sherif to run your packager manager's `install` command after running autofix, you can use the `--no-install` flag: 
```

2024-08-10 07:04 UTC, QuiiBz commented on README.md
> +## No-install mode
Let's move this under the `Autofix` section
```suggestion
### No-install mode
```

2024-08-24 09:20 UTC, QuiiBz approved these changes
I added a few commits to add support for Bun & refactor a bit the code. Tested and seems to work fine, so I'll merge this soon. Thanks again for the help!

2024-08-25 15:07 UTC, Willem-Jaap commented
Great! Looking forward to having this merged

2024-08-25 17:38 UTC, merged